version: '3'
services:
  build-environment:
    image: golang:1.20.0
    platform: linux/amd64
    volumes:
      - ../:/go/src/github.com/ccbrown/gggtracker
    working_dir: /go/src/github.com/ccbrown/gggtracker/aws-sam
  lambda-environment:
    entrypoint: []
    environment:
      LD_LIBRARY_PATH: ''
    image: lambci/lambda:go1.x
    platform: linux/amd64
    volumes:
      - ../:/go/src/github.com/ccbrown/gggtracker
    working_dir: /go/src/github.com/ccbrown/gggtracker/aws-sam
